version: '3'
services:

    mfc-redis:
        image: redis:5.0-alpine
        container_name: mfc-redis
        command: ["redis-server", "--appendonly", "yes"]
        hostname: redis
        ports:
            - 6379:6379
        volumes:
            - ./database/storage/redis-data:/data
            
    mfc-mysql:
        image: mysql:8.0.21
        container_name: mfc-mysql
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - 3306:3306
        environment:
            - MYSQL_DATABASE=person
            - MYSQL_ROOT_PASSWORD=de2543d4a8fb4176bdc9faf789ad79e6
        volumes:
            - ./database/mysql-db:/docker-entrypoint-initdb.d
            - ./database/storage/.db:/var/lib/mysql